version: '3'

services:
    client:
        container_name: client
        build: ./client
        volumes:
          - ./client:/var/www/client
        ports:
          - 3000:3000
        environment:
          - NODE_ENV=development
    scraper:
        container_name: scraper
        build: ./services/scraper
        volumes: 
          - ./services/scraper:/services/scraper
        ports:
            - "8081:8081"
    stockdata:
        container_name: stockdata
        build: ./services/stockdata
        volumes: 
          - ./services/stockdata:/services/stockdata
        ports:
            - "8082:8082"
    calculator:
        container_name: calculator
        build: ./services/calculator
        volumes: 
          - ./services/calculator:/services/calculator
        ports:
            - "8083:8083"
