version: '3'

services:
    scraper:
        build: services/scraper
        ports:
            - "8081:8081"
    stockdata:
        build: services/stockdata
        ports:
            - "8082:8082"
